#!/usr/bin/env python3

colors = {
    "paleyellow_1": "#ffffea",
    "paleyellow_2": "#f2f2dd",
    "paleyellow_3": "#eeeed9",
    "paleyellow_4": "#777770",
    "gray_1": "#f6f6f6",
    "gray_2": "#eeeeee",
    "gray_3": "#e8e8e8",
    "gray_4": "#888888",
    "black": "#000000",
    "white": "#ffffff",
    "red_1": "#bb5d5d",
    "red_2": "#dd8888",
    "orange_1": "#c78f67",
    "orange_2": "#f8dfc8",
    "yellow_1": "#99884c",
    "yellow_2": "#eeee9e",
    "green_1": "#558855",
    "green_2": "#a8cca8",
    "green_3": "#eaffea",
    "cyan_1": "#5aaaaa",
    "cyan_2": "#8ccccc",
    "cyan_3": "#9eeeee",
    "cyan_4": "#eaffff",
    "blue_1": "#4670bb",
    "blue_2": "#afdbff",
    "blue_3": "#cbe7ff",
    "blue_4": "#ebf5ff",
    "purple_1": "#8888cc",
    "purple_2": "#bbbbff",
    "magenta_1": "#aa6688",
    "magenta_2": "#d08eaa",
    "border_1": "#00000058",
    "border_2": "#000000cc",
    "invisible": "#00000000",
    # Warm dark backgrounds
    "darkbrown_1": "#1a1612",
    "darkbrown_2": "#211d18",
    "darkbrown_3": "#2a2520",
    "darkbrown_4": "#6a5f50",
    # Warm dark teals (UI)
    "darkteal_1": "#1a1f1f",
    "darkteal_2": "#2d4747",
    # Warm highlights
    "warmgold_1": "#4a4020",
    "warmgold_2": "#3d3520",
    # Warm foregrounds
    "warmbeige_1": "#d4c5a9",
    "warmbeige_2": "#f5f0e8",
    # Muted purples for dark
    "purple_muted": "#7070a0",
    "purple_dark": "#4a3d5a",
    # Cool dark backgrounds
    "darkgray_1": "#1a1d23",
    "darkgray_2": "#21252b",
    "darkgray_3": "#2c313a",
    "darkgray_4": "#5a6270",
    "darkgray_5": "#383f4a",
    # Cool dark blues (UI)
    "darkblue_1": "#1e2228",
    "darkblue_2": "#2d3e50",
    "darkblue_3": "#2d4a6a",
    # Cool foregrounds
    "coolgray_1": "#c8ccd4",
    "coolgray_2": "#e8eef5",
    # Muted blue
    "blue_muted": "#5a7aa0",
}

base = {
    **colors,
    "type": "light",
    "blank_bg": colors["white"],
    "popup_bg": colors["white"],
    "fg": colors["black"],
    "fg_dim": colors["black"] + "78",
    "fg_faint": colors["black"] + "40",
    "fg_ghost": colors["black"] + "20",
    "neutral_hl": colors["black"] + "10",
    "badge_bg": colors["purple_1"],
    "badge_fg": colors["white"],
    "button_bg": colors["purple_1"],
    "button_fg": colors["white"],
}

dark_acme_base = {
    **colors,
    "type": "dark",
    "blank_bg": colors["darkbrown_1"],
    "popup_bg": colors["darkbrown_3"],
    "fg": colors["warmbeige_1"],
    "fg_dim": colors["warmbeige_1"] + "78",
    "fg_faint": colors["warmbeige_1"] + "40",
    "fg_ghost": colors["warmbeige_1"] + "20",
    "neutral_hl": colors["warmbeige_1"] + "10",
    "badge_bg": colors["purple_muted"],
    "badge_fg": colors["warmbeige_2"],
    "button_bg": colors["purple_muted"],
    "button_fg": colors["warmbeige_2"],
    "border_1": colors["warmbeige_1"] + "58",
    "border_2": colors["warmbeige_1"] + "cc",
}

dark_white_base = {
    **colors,
    "type": "dark",
    "blank_bg": colors["darkgray_1"],
    "popup_bg": colors["darkgray_3"],
    "fg": colors["coolgray_1"],
    "fg_dim": colors["coolgray_1"] + "78",
    "fg_faint": colors["coolgray_1"] + "40",
    "fg_ghost": colors["coolgray_1"] + "20",
    "neutral_hl": colors["coolgray_1"] + "10",
    "badge_bg": colors["blue_muted"],
    "badge_fg": colors["coolgray_2"],
    "button_bg": colors["blue_muted"],
    "button_fg": colors["coolgray_2"],
    "border_1": colors["coolgray_1"] + "58",
    "border_2": colors["coolgray_1"] + "cc",
}

themes = [
    {
        **base,
        "name": "Acme",
        "bg_1": colors["paleyellow_1"],
        "bg_2": colors["paleyellow_2"],
        "bg_3": colors["paleyellow_3"],
        "ui_bg": colors["cyan_4"],
        "ui_hl": colors["cyan_3"],
        "match_bg": colors["yellow_2"] + "ee",
        "match_focus_bg": colors["purple_2"] + "aa",
        "selection_bg": colors["yellow_2"] + "ee",
        "gray": colors["paleyellow_4"],
    },
    {
        **base,
        "name": "Acme White",
        "bg_1": colors["white"],
        "bg_2": colors["gray_1"],
        "bg_3": colors["gray_2"],
        "ui_bg": colors["blue_4"],
        "ui_hl": colors["blue_2"],
        "match_bg": colors["orange_2"] + "ee",
        "match_focus_bg": colors["blue_3"] + "ee",
        "selection_bg": colors["gray_3"],
        "gray": colors["gray_4"],
        "yellow_2": colors["orange_2"],
    },
    {
        **dark_acme_base,
        "name": "Dark Acme",
        "bg_1": colors["darkbrown_1"],
        "bg_2": colors["darkbrown_2"],
        "bg_3": colors["darkbrown_3"],
        "ui_bg": colors["darkteal_1"],
        "ui_hl": colors["darkteal_2"],
        "match_bg": colors["warmgold_1"] + "ee",
        "match_focus_bg": colors["purple_dark"] + "aa",
        "selection_bg": colors["warmgold_2"] + "ee",
        "gray": colors["darkbrown_4"],
    },
    {
        **dark_white_base,
        "name": "Dark Acme White",
        "bg_1": colors["darkgray_1"],
        "bg_2": colors["darkgray_2"],
        "bg_3": colors["darkgray_3"],
        "ui_bg": colors["darkblue_1"],
        "ui_hl": colors["darkblue_2"],
        "match_bg": colors["warmgold_1"] + "ee",
        "match_focus_bg": colors["darkblue_3"] + "ee",
        "selection_bg": colors["darkgray_5"],
        "gray": colors["darkgray_4"],
    },
]

